const actionTypes = {
	AUTHENTICATE_PHONE: 'AUTHENTICATE_PHONE',
	AUTHENTICATE_PHONE_SUCCESS: 'AUTHENTICATE_PHONE_SUCCESS',
	AUTHENTICATE_PHONE_FAILURE: 'AUTHENTICATE_PHONE_FAILURE',

	VERIFY_PHONE:"VERIFY_PHONE",
	VERIFY_PHONE_SUCCESS:"VERIFY_PHONE_SUCCESS",
	VERIFY_PHONE_FAILURE:"VERIFY_PHONE_FAILURE",

	UPLOAD_PICTURE:"UPLOAD_PICTURE",
	UPLOAD_PICTURE_SUCCESS:"UPLOAD_PICTURE_SUCCESS",
	UPLOAD_PICTURE_FAILURE:"UPLOAD_PICTURE_FAILURE",

	CREATE_USER_DETAILS:"CREATE_USER_DETAILS",
	CREATE_USER_DETAILS_SUCCESS:"CREATE_USER_DETAILS_SUCCESS",
	CREATE_USER_DETAILS_FAILURE:"CREATE_USER_DETAILS_FAILURE",


	//

	CREDIT_USER:"CREDIT_USER",
	CREDIT_USER_SUCCESS:"CREDIT_USER_SUCCESS",
	CREDIT_USER_FAILURE:"CREDIT_USER_FAILURE",

	UPDATE_USER_EMAIL:"UPDATE_USER_EMAIL",
	UPDATE_USER_EMAIL_SUCCESS:"UPDATE_USER_EMAIL_SUCCESS",
	UPDATE_USER_EMAIL_FAILURE:"UPDATE_USER_EMAIL_FAILURE",

	UPDATE_USER_PASSWORD:"UPDATE_USER_PASSWORD",
	UPDATE_USER_PASSWORD_SUCCESS:"UPDATE_USER_PASSWORD_SUCCESS",
	UPDATE_USER_PASSWORD_FAILURE:"UPDATE_USER_PASSWORD_FAILURE",


	// update  user password

	GET_RIDER_DETAILS:"GET_RIDER_DETAILS",
	GET_RIDER_DETAILS_SUCCESS:"GET_RIDER_DETAILS_SUCCESS",
	GET_RIDER_DETAILS_FAILURE:"GET_RIDER_DETAILS_FAILURE",


	UPDATE_RIDER_STATUS:"UPDATE_RIDER_STATUS",
	UPDATE_RIDER_STATUS_SUCCESS:"UPDATE_RIDER_STATUS_SUCCESS",
	UPDATE_RIDER_STATUS_FAILURE:"UPDATE_RIDER_STATUS_FAILURE",

	ADD_RIDER:"ADD_RIDER",
	ADD_RIDER_SUCCESS:"ADD_RIDER_SUCCESS",
	ADD_RIDER_FAILURE:"ADD_RIDER_FAILURE",
	
	SEND_NOTIFICATION:"SEND_NOTIFICATION",
	SEND_NOTIFICATION_SUCCESS:"SEND_NOTIFICATION_SUCCESS",
	SEND_NOTIFICATION_FAILURE:"SEND_NOTIFICATION_FAILURE",
	
	GET_ADMIN:"GET_ADMIN",
	GET_ADMIN_SUCCESS:"GET_ADMIN_SUCCESS",
	GET_ADMIN_FAILURE:"GET_ADMIN_FAILURE",

	TOP_USERS:"TOP_USERS",
	TOP_USERS_SUCCESS:"TOP_USERS_SUCCESS",
	TOP_USERS_FAILURE:"TOP_USERS_FAILURE",

	ACCOUNT_SET_UP_DONE:"ACCOUNT_SET_UP_DONE",
	ACCOUNT_SET_UP_DONE_SUCCESS:"ACCOUNT_SET_UP_DONE_SUCCESS",
	ACCOUNT_SET_UP_DONE_FAILURE:"ACCOUNT_SET_UP_DONE_FAILURE",

	LOGIN:"LOGIN",
	LOGIN_SUCCESS:"LOGIN_SUCCESS",
	LOGIN_FAILURE:"LOGIN_FAILURE",


	ALL_USERS:"ALL_USERS",
	ALL_USERS_SUCCESS:"ALL_USERS_SUCCESS",
	ALL_USERS_FAILURE:"ALL_USERS_FAILURE",



};

export default actionTypes;