export const GOOGLE_LOGIN = 'GOOGLE_LOGIN';
export const GOOGLE_LOGIN_SUCCESS = 'GOOGLE_LOGIN_SUCCESS';
export const GOOGLE_LOGIN_FAILURE = 'GOOGLE_LOGIN_FAILURE';

export const CHANGE_LOGIN_STATUS = 'CHANGE_LOGIN_STATUS';
export const CHANGE_LOGIN_STATUS_SUCCESS = 'CHANGE_LOGIN_STATUS_SUCCESS';
export const CHANGE_LOGIN_STATUS_FAILURE = 'CHANGE_LOGIN_STATUS_FAILURE';